# Generated by Django 5.2.7 on 2025-10-29 12:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIDatasetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jumlah_data', models.IntegerField(blank=True, null=True)),
                ('sumber_data', models.CharField(blank=True, max_length=100, null=True)),
                ('versi_model', models.CharField(blank=True, max_length=20, null=True)),
                ('akurasi_model', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(default='Training', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Operator', 'Operator'), ('SPV', 'Supervisor'), ('AOCH', 'AOCH'), ('GM', 'General Manager'), ('Admin', 'Admin')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Peralatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peralatan', models.CharField(max_length=150)),
                ('kode_peralatan', models.CharField(max_length=30, unique=True)),
                ('kategori', models.CharField(blank=True, max_length=50, null=True)),
                ('merk', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('tahun_pengadaan', models.IntegerField(blank=True, null=True)),
                ('status_operasional', models.CharField(choices=[('Normal', 'Normal'), ('Serviceable', 'Serviceable'), ('Unserviceable', 'Unserviceable'), ('Tidak Normal', 'Tidak Normal')], default='Normal', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SettingAIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_model', models.CharField(max_length=100)),
                ('versi', models.CharField(max_length=20)),
                ('akurasi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('path_model', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_unit', models.CharField(max_length=100)),
                ('kode_unit', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('lokasi', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(max_length=150)),
                ('tabel_terkait', models.CharField(blank=True, max_length=50, null=True)),
                ('id_referensi', models.IntegerField(blank=True, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='NilaiKesiapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kategori_kesiapan', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Diverifikasi SPV', 'Diverifikasi SPV'), ('Diverifikasi AOCH', 'Diverifikasi AOCH'), ('Butuh Verif GM', 'Butuh Verif GM'), ('Final', 'Final')], default='Draft', max_length=30)),
                ('butuh_verif_gm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_by', to='core.appuser')),
                ('peralatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.peralatan')),
            ],
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('pesan', models.TextField()),
                ('jenis', models.CharField(choices=[('Kesiapan', 'Kesiapan'), ('Verifikasi', 'Verifikasi'), ('Peralatan', 'Peralatan'), ('AI Insight', 'AI Insight')], default='Kesiapan', max_length=30)),
                ('status_baca', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=255)),
                ('path_file', models.CharField(max_length=255)),
                ('jenis_file', models.CharField(choices=[('Foto', 'Foto'), ('Dokumen', 'Dokumen'), ('Lainnya', 'Lainnya')], default='Foto', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appuser')),
                ('kesiapan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.nilaikesiapan')),
                ('peralatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.peralatan')),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatPeralatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_riwayat', models.CharField(choices=[('Perawatan', 'Perawatan'), ('Perbaikan', 'Perbaikan'), ('Downtime', 'Downtime'), ('Kalibrasi', 'Kalibrasi')], max_length=20)),
                ('tanggal_mulai', models.DateField(blank=True, null=True)),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('hasil', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Selesai', 'Selesai'), ('Proses', 'Proses'), ('Dijadwalkan', 'Dijadwalkan')], default='Proses', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appuser')),
                ('peralatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.peralatan')),
            ],
        ),
        migrations.AddField(
            model_name='peralatan',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit'),
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('Harian', 'Harian'), ('Mingguan', 'Mingguan'), ('Bulanan', 'Bulanan')], max_length=10)),
                ('tanggal_awal', models.DateField()),
                ('tanggal_akhir', models.DateField()),
                ('rata_kesiapan', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('distribusi_kategori', models.JSONField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appuser')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit')),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit'),
        ),
        migrations.CreateModel(
            name='AIAnalitik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField()),
                ('hasil_prediksi', models.CharField(blank=True, max_length=150, null=True)),
                ('faktor_penyebab', models.TextField(blank=True, null=True)),
                ('saran_tindakan', models.TextField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dibuat_otomatis', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Verifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifikasi_level', models.CharField(choices=[('SPV', 'SPV'), ('AOCH', 'AOCH'), ('GM', 'GM')], max_length=10)),
                ('status_verifikasi', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('tanggal_verifikasi', models.DateTimeField(default=django.utils.timezone.now)),
                ('kesiapan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nilaikesiapan')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_verif', to='core.appuser')),
                ('verifikator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikator', to='core.appuser')),
            ],
        ),
    ]
