# Generated by Django 5.2.7 on 2025-11-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilaikesiapan',
            name='jumlah_alat_normal',
            field=models.PositiveIntegerField(default=0, help_text='Jumlah alat berstatus normal/serviceable.'),
        ),
        migrations.AddField(
            model_name='peralatan',
            name='jumlah_alat',
            field=models.PositiveIntegerField(default=1, help_text='Total alat yang dimiliki unit ini.'),
        ),
    ]
