# Generated by Django 5.2.7 on 2025-11-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nilaikesiapan_jumlah_alat_normal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaikesiapan',
            name='jumlah_alat_normal',
            field=models.PositiveIntegerField(default=1, help_text='Jumlah alat berstatus normal/serviceable.'),
        ),
    ]
