# Generated by Django 5.2.7 on 2025-11-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_nilaikesiapan_jumlah_alat_normal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peralatan',
            name='kategori',
            field=models.CharField(blank=True, choices=[('Prioritas', 'Prioritas'), ('Non Prioritas', 'Non Prioritas')], default='Prioritas', max_length=20, null=True),
        ),
    ]
