# Generated by Django 5.2.7 on 2025-11-04 23:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_peralatan_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaikesiapan',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
