# Generated by Django 5.2.7 on 2025-11-07 02:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appuser_updated_at_fileupload_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bandara', models.CharField(default='BIZAM', max_length=100)),
                ('faktor_kali_kwh', models.DecimalField(decimal_places=2, default=8000, max_digits=10)),
                ('harga_lwbp', models.DecimalField(decimal_places=2, default=1035.78, max_digits=12)),
                ('harga_wbp', models.DecimalField(decimal_places=2, default=1553.67, max_digits=12)),
                ('batas_pemakaian_harian', models.DecimalField(decimal_places=2, default=30000, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KonsumsiEnergi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.localdate)),
                ('stand_awal_lwbp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stand_akhir_lwbp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stand_awal_wbp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stand_akhir_wbp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pemakaian_lwbp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pemakaian_wbp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pemakaian_energi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('biaya_lwbp', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('biaya_wbp', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_biaya', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('selisih_pemakaian_biaya', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deviasi_pemakaian_persen', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
