# Generated by Django 5.2.7 on 2025-11-15 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notifikasi_link_notifikasi_related_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilaikesiapan',
            name='verifikator_aoch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verif_aoch', to='core.appuser'),
        ),
        migrations.AddField(
            model_name='nilaikesiapan',
            name='verifikator_gm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verif_gm', to='core.appuser'),
        ),
        migrations.AddField(
            model_name='nilaikesiapan',
            name='verifikator_spv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verif_spv', to='core.appuser'),
        ),
    ]
